### ISSUE TITLE
Keyword mapping

### ISSUE THREAD

**Issue by Simn** [waneck/haxe-genc#19]
Shouldn't be too many, but we have to handle things like sizeof.

**Comment by Simn** [comment]
We have to identify where we have to map keywords. Fields should not be a problem as they are generated as Type_fieldName anyway, so I suppose this leaves variables and ...?

**Comment by waneck** [comment]
Non-function fields still need to be remapped also

**Comment by Simn** [comment]
What do you mean "non-function fields"?

**Comment by waneck** [comment]
Member field vars

**Comment by Simn** [comment]
Why would these be any different from methods?

**Comment by Simn** [comment]
Well, because they are I suppose. You are right of course.
