### ISSUE TITLE
Handle TObjectDecl

### ISSUE THREAD

**Issue by Simn** [waneck/haxe-genc#2]
... somehow.

**Comment by Simn** [comment]
@waneck: How do you do this in Java?

My idea would be to build a signature string (field names + type names, ordered by field name) for each object declaration and enumerate that, so we get structs for hx_obj_1, hx_obj_2 etc.

**Comment by Simn** [comment]
The code I've committed generates something like this:

https://gist.github.com/Simn/0adf38050323abc61fc9

This still needs a dependency checker and then some forward declarations of used pointer types, but so far I'm pretty happy.

**Comment by waneck** [comment]
That's a good first look at it. I'd drop the centralized struct declarations at AnonTypes.h, and would declare them locally.
Also, unfortunately AFAIK there won't really be a good way to access anonymous types without reflection / interfaces, so accessing them will probably need to be done over reflection, when it is implemented.

**Comment by Simn** [comment]
You can't declare them locally, that would introduce dependencies between files and introduce quite a dependency mess. Seems much better to have them all in one file for now.

What do you mean "access anonymous types without reflection / interfaces"?

**Comment by waneck** [comment]
Take for example the following code:

```
typedef APoint =
{
    x:Float,
    y:Float
}

class Point
{
    public var name:String; //just to break compatibility ;)
    public var x:Float;
    public var y:Float;
    public function new(x,y) { this.x = x; this.y = y; }
}

var p:APoint;

if (something)
{
    p = new Point(10,10);
} else {
    p = { x:10, y:10 };
}

trace(p.x);

return p;
```

How would `p` be typed in C? We can't type as anon, otherwise if it's a real Point, it isn't compatible with hx_anon. Instead, we'd have to either create a hidden interface and implement on both Point and hx_anon, and use that interface, or access through reflection.

I don't understand why declaring hx_anons locally would introduce a dependency mess? Actually seems to me that a dependency mess is much more likely when you centralize (any anonymous type change will trigger a recompile in all files that use anonymous types) than when you don't

**Comment by Simn** [comment]
Any new insights here? That `p` issue is a bit scary as I cannot see a clean solution. We could optimize it if alignment is given, but we'll need to pull some tricks in other cases.

Regarding the dependency mess, my thinking was that declaring anon types locally would introduce dependencies between types through that anon. However, you're right about this also being the case if they are declared centralized.

**Comment by ousado** [comment]
The recompilation issue could be addressed by having one file per anon type. I don't see a good reason, and it feels quite ugly, to declare one and the same type N times, along with defining the constructor functions etc. all over again.

**Comment by Simn** [comment]
I agree we can change that. I made it like that before we had the dependency handling code we have now so it would be easier to get this right, but there should be no reason to not separate them.
