### ISSUE TITLE
Keep going?

### ISSUE THREAD

**Issue by Simn** [waneck/haxe-genc#22]
We got pretty far and then just stopped. Who's still with me?

**Comment by deltaluca** [comment]
hurah!

**Comment by m22spencer** [comment]
Only an observer for now, but hell yes keep going

**Comment by waneck** [comment]
Sorry about that, I feel that this was partly my fault.
It would be nice to start building a schedule for that - I'd like to get back to it after 3.1, but I'm not sure anymore when it's scheduled to happen.
I'd be thrilled to get back to it again :)

**Comment by ousado** [comment]
Same here, well, actually I feel it's entirely my fault, to be honest
Either way, still with you. I've spent some time on region inference and GC in the last 2 weeks, not as much as I had hoped to, but I'm on it.

**Comment by Simn** [comment]
It's hard to come up with a schedule for this, there are still a few core issues to resolve and I can't really estimate how long these are going to take. Also, it's hard to tell how much time you guys have for this project.

Last year I made a show of committing pattern matching on 6 December and it would be great to commit a initial, somewhat working C target out of nowhere this year. That's almost three months from now and I think it should be enough time.

**Comment by Simn** [comment]
\o/
