### ISSUE TITLE
Optional struct args.

### ISSUE THREAD

**Issue by deltaluca** [waneck/haxe-genc#28]
I don't know if we're supposed to support them yet, but the following fails:

``` haxe
var x:{?y:Int} = {y:20};
trace(x.y); // segfault
x = {};
trace(x.y); // segfault too.
```

**Comment by Simn** [comment]
The second trace still segfaults because we cannot trace `null` at the moment.

**Comment by deltaluca** [comment]
You say that, but I have managed to get (null) to trace out before :) Probably for another reason of trace not being properly implemented yet, maybe it was printing NULL through %s and that gives (null)
