### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by Simn** [waneck/haxe-genc#3]
General exception handling is going to require quite some runtime support I suppose.

We _could_ do some local checking to handle `try throw catch` patterns in a goto-way, but that might not be worth it.

**Comment by waneck** [comment]
This one should be handled with lonjmp, imho
http://en.wikipedia.org/wiki/Setjmp.h

**Comment by Simn** [comment]
Yes, although I'm worried about the stack unwinding and general GC.

**Comment by waneck** [comment]
Ah, I see!
if we don't use 'destructors' on stack-allocated instances, I'm not sure we
will have a problem with stack unwinding. I might be wrong, though

**Comment by waneck** [comment]
I found this:
http://stackoverflow.com/questions/15464891/is-it-possible-to-write-a-zero-cost-exception-handling-in-c

seems like at least for gcc, we could try to achieve an even lighter approach to exceptions. The only problem I see is that gcc uses trampolines to be able to achieve this, which means that we can't set the stack as NX

**Comment by waneck** [comment]
seems not really worth the trouble, though

**Comment by Simn** [comment]
I think using setjmp is good. We just have to figure out the best way of maintaining a stack of nested exceptions with different catch-types.

**Comment by Simn** [comment]
This is basically done. We'll need to add some additional checks once we have Std.is working, but I'll close this for now.
