### ISSUE TITLE
Iterators

### ISSUE THREAD

**Issue by Simn** [waneck/haxe-genc#4]
I suspect these will be quite annoying to get right.

**Comment by waneck** [comment]
If we actually get a good way to deal with dynamic access directly from the vtable, Iterators may not even have to be a special case.
Anyway, what I plan to do on Java/C# is to force a Iterator / Iterable interface implementation when iterator/hasNext/next functions are detected. Also transform anonymous object declaration into a real class, when functions are declared as well.

**Comment by Simn** [comment]
Indeed, iterators are no special case. I thought we might have to pull some tricks to support TFor, but it's actually just a TWhile with proper access on next and hasNext fields.
