### ISSUE TITLE
Determine project priorities

### ISSUE THREAD

**Issue by Simn** [waneck/haxe-genc#8]
First step: Collect project priorities
Second step: Discuss and order them

I'll start (unordered):
- performance (static)
- performance (dynamic)
- generated code size
- memory consumption
- readability of generated code
- conformance to haxe "standard"
- correctness
- implementation difficulty (for us)
- implementation difficulty (for custom native APIs)
- native code interoperability
- cross-platform
- self-contention
- compilation speed

**Comment by waneck** [comment]
Are we collecting priorities or discussing them already? :)
I'm thinking but I guess I have no priority to add, apart from the ones you mentioned.

One thing that you may have already mentioned (it's not clear to me), is also native code interop

**Comment by Simn** [comment]
Just collecting for now.

I've added native code interop.

**Comment by deltaluca** [comment]
Can we even call it a haxe target, if it does not conform to haxe standard and is not 'correct'?

id put dynamic performance at bottom of the pile :)

**Comment by Simn** [comment]
hxcpp still has some failing haxe unit tests as well. There could be corner cases where conforming might have a huge negative impact on another priority. It may then make sense to introduce a compiler switch which influences this. (I'm not arguing for that, just to clarify why these points are in the list.)

**Comment by waneck** [comment]
I'm not sure if it makes sense to add those, but it came into my mind as something important to me (though they will hardly collide with any others)
- cross-platform
- self-contention

**Comment by Simn** [comment]
I added these, as well as "compilation speed".

These should be enough for now, I'll define and explain my ordering now.

**Comment by Simn** [comment]
1. correctness
2. cross-platform
3. performance (static)
4. conformance to haxe "standard"
5. implementation difficulty (for custom native APIs)
6. native code interoperability
7. memory consumption
8. self-contention
9. performance (dynamic)
10. generated code size
11. readability of generated code
12. compilation speed
13. implementation difficulty (for us)

_Correctness_ is pretty much a given and it's hard to argue against it in any way. Likewise, this thing should run _cross-platform_ without any problems whatsoever.

I put _static performance_ before _haxe conformance_ because I'm willing to introduce subtle differences if that allows for fast static code. At the moment, some generators have error messages like "This expression cannot be compiled to Javascript", which is what I'm getting at here. If some rare expression is too hard to compile correctly without affecting general performance, it's okay to not support it.

Moving on, I consider it quite important to keep _custom API implementation_ simple, and in a related fashion I'd like to have simple _native code interoperability_. I put that above _memory consumption_ because I'd be willing to sacrifice quite some memory to achieve this.

_Self-contention_ is more important than _dynamic performance_ in my opinion. We wouldn't want to increase complexity here much just for that. However, it trumps _generated code size_ because increased performance of any kind warrants more generated code in my opinion.

A decent _readability of generated code_ allows some native debugging, which can be useful especially in the early days of this project.

_Compilation speed_ is not a big issue for me because the speed of the generator does not affect haxe completion. We should still try to keep native compilation as small as possible at the expense of generating some makefile, but that should be enough.

Lastly, we are totally unimportant and so is _our implementation difficulty_.

**Comment by waneck** [comment]
- correctness
- conformance to haxe "standard"
- performance (static)
- generated code size
- cross-platform
- native code interoperability
- self-contention
- memory consumption
- performance (dynamic)
- readability of generated code
- implementation difficulty (for custom native APIs)
- compilation speed
- implementation difficulty (for us)

I'm still not sure where would there be any place to diverge from haxe "standard", but I guess if there's a very good reason to do it, I'd might choose the performance side. Just didn't want conformance to haxe standard to be too far away :)

Static performance comes next, but for me it's almost equally important to have an option to have a small generated code size, as sometimes optimization for size is still a better optimization. So as discussed yesterday, a flag for "optimize for code size" and "optimize for speed" would be great, imho.

Cross-platform is very important, but I'm willing to create optimized fast tracks for some platforms/compilers. A slower but cross-platform solution would still be needed in that sensem though.

While I think there are legitimate reasons for dynamic performance to be important (e.g. serialization, json, etc), I wouldn't like to sacrifice any of the former topics to optimize dynamic performance. Also the scheme I'm thinking will probably make very fast dynamic access with probably the least code overhead from other solutions I can think of. Specially comparing with hxcpp.

For me, generated code readability isn't so necessary, and nor is implementation difficulty for native APIs. I'd rather be able to communicate with native code from Haxe than worrying about the other way around. Specially as this may get very difficult if we use a precise GC. Compilation speed isn't also a concern of mine (look at my targets :P, and they can always be optimized later)

Lastly, we are totally unimportant and so is our implementation difficulty.[2]
